name: GitHub pages deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deps
        run: |
          npm ci
          npm install -g @angular/cli
          export PATH="$HOME/.npm-global/bin:$PATH"

      - name: deploy
        run: |
          ng deploy --cname=www.hackphs.tech
