name: Angular CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Deps
        run: |
          npm ci
          npm install -g @angular/cli
          export PATH="$HOME/.npm-global/bin:$PATH"

      - name: Deploy to GitHub Pages
        run: ng deploy --cname=www.hackphs.tech --name="Zelo-S" --email=stevethesteve990@gmail.com

      - name: Checkout
        uses: actions/checkout@v1

      - name: Karma Unit tests
        run: ng test
